torchrun --nproc_per_node=4 your_model_train_shell \ 
    --model_name_or_path your_model_path \
    --data_path your_model_train_dataset_path \
    --bf16 True \
    --output_dir test \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "no" \
    --learning_rate 1e-3 \
    --weight_decay 0.0 \
    --warmup_ratio 0.1 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 1024 \
    --lazy_preprocess True \
    --medusa_num_heads 3 \
    --medusa_num_layers 1